CREATE TABLE PUBLIC.WEATHER[
ID numeric NOT NULL AUTO_INCREMENT,
NAME varchar(50) NOT NULL,
WMOCODE numeric(5) NOT NULL,
AIR numeric(3,1) NOT NULL,
WIND numeric(3,1) NOT NULL,
PHENOMENON varchar(50) NOT NULL,
QUERYTIME TIMESTAMP NOT NULL default CURRENT_TIMESTAMP,
PRIMARY KEY ID
];